const imageConceptMap = {
  'img-1.jpg': 'LIBERTAD',
  'img-2.jpg': 'FUGACIDAD',
  'img-3.jpg': 'REFUGIO',
  'img-4.jpg': 'EXPLORACIÓN',
  'img-5.jpg': 'CONSTRUCCIÓN',
  'img-6.jpg': 'INTEGRIDAD',
  'img-7.jpg': 'ETÉREO',
  'img-8.jpg': 'NO-SIMETRÍA',
  'img-9.jpg': 'PRIMITIVO',
  'img-10.jpg': 'MASIVIDAD',
  'img-11.jpg': 'PROTECCIÓN',
  'img-12.jpg': 'ORGÁNICO',
  'img-13.jpg': 'COMUNITARIO',
  'img-14.jpg': 'AMBIGÜEDAD',
  'img-15.jpg': 'SILENCIO',
  'img-16.jpg': 'CLAROS',
  'img-17.jpg': 'CALIDEZ',
  'img-18.jpg': 'PLURALIDAD',
  'img-19.jpg': 'ABIERTO',
  'img-20.jpg': 'INTROSPECCIÓN',
  'img-21.jpg': 'MULTIPLICIDAD',
  'img-22.jpg': 'REFLEJO',
  'img-23.jpg': 'INTEGRIDAD',
  'img-24.jpg': 'CONSTRUCCIÓN',
};